// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: deps/services/push-sender/grpc/push-sender.proto

package push_sender

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PushSenderClient is the client API for PushSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushSenderClient interface {
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
}

type pushSenderClient struct {
	cc grpc.ClientConnInterface
}

func NewPushSenderClient(cc grpc.ClientConnInterface) PushSenderClient {
	return &pushSenderClient{cc}
}

func (c *pushSenderClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, "/push_sender.PushSender/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushSenderServer is the server API for PushSender service.
// All implementations must embed UnimplementedPushSenderServer
// for forward compatibility
type PushSenderServer interface {
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	mustEmbedUnimplementedPushSenderServer()
}

// UnimplementedPushSenderServer must be embedded to have forward compatible implementations.
type UnimplementedPushSenderServer struct {
}

func (UnimplementedPushSenderServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedPushSenderServer) mustEmbedUnimplementedPushSenderServer() {}

// UnsafePushSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushSenderServer will
// result in compilation errors.
type UnsafePushSenderServer interface {
	mustEmbedUnimplementedPushSenderServer()
}

func RegisterPushSenderServer(s grpc.ServiceRegistrar, srv PushSenderServer) {
	s.RegisterService(&PushSender_ServiceDesc, srv)
}

func _PushSender_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushSenderServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push_sender.PushSender/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushSenderServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PushSender_ServiceDesc is the grpc.ServiceDesc for PushSender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushSender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "push_sender.PushSender",
	HandlerType: (*PushSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _PushSender_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deps/services/push-sender/grpc/push-sender.proto",
}
